#!/usr/bin/python

import json
import os
import sys
import urllib2

api_base = 'https://api.digitalocean.com/v2'


def usage():
    print('{0} [Floating IP]'.format(sys.argv[0]))
    print('\nYour DigitalOcean API token must be in the "DO_TOKEN"'
          ' environmental variable.')


def main(floating_ip):
    payload = {'type': 'unassign'}
    headers = {'Authorization': 'Bearer {0}'.format(os.environ['DO_TOKEN']),
               'Content-Type': 'application/json'}

    url = api_base + '/floating_ips/{0}/actions'.format(floating_ip)
    params = json.dumps(payload).encode('utf8')

    request = urllib2.Request(url, headers=headers, data=params)
    response = urllib2.urlopen(request)

    result = json.loads(response.read().decode('utf8'))
    if 'message' in result:
        print('{0}: {1}'.format(result['id'], result['message']))
        sys.exit(1)
    else:
        print('Unassigning IP address: {0}'.format(result['action']['status']))

if __name__ == '__main__':
    if 'DO_TOKEN' not in os.environ or not len(sys.argv) > 2:
        usage()
        sys.exit()

    main(sys.argv[1])
